language: elixir
elixir:
- 1.2.0
after_success:
- MIX_ENV=test mix coveralls.travis
notifications:
  slack:
    secure: SPvOIJ1GcVbU4o4XIV7E0NajNrYYXlGYhk7MBOlsh9cSX5Y/eqVXyjVQu5WSuo+NrSlPeoN+lVd5D3hLjPyZMPP80WUjKMExBK1xHB3ZaXLqTprdtiJOn4cFEjEWQZSJ0je33A9p2L3MIQQtWN2I6u8VV6FYPMDJRrczBEoWliREfY2ETfOyAcvLbVP9UfzvGjI7/P9KWUHnlRAta5/uGqyIXQkF5NbVwD5j0qJgtW+yufXUuA4DZtvFfOBJUM68C8ZHl4lyTOfjECpwtBx7Rrkb/vq+Y7GT6ASi+hUNh1kfHJI8piUDvKjNhCXf/k5L/oMbfuVox6u9/L2grrcTrj+lHk3R041/URNI5lzNYZ4pAQFRjw+gkZ74kWXfmKAynF2htrtr+gO+fgzhWMuDKCdWyqUau11yezkkac45LQs62d73R6D2etHwPScBT1Au2CwAG7ZYdx/4ywEsykFmlutYIj5uJOgoqpdgYhOQVwzwd/p8IWEP3TIJv41xk4nECuRxacE8DKbHrNbDnTRKmV91qFGd6YmXLzZ6n2TGDgvZbykwzWo1MWdOO5vXtUw2CkQoWN+vm+16fVMciKxjsD801ub1FHuxu0ZNmo65WApK/HX2VpzzydrVMn6Oc+G3Ilqr2t4laywJPxs6ad3l19fmAnxnemrbEs6+hwlyXE8=
